### ISSUE TITLE
Move to JuliaArrays or JuliaImages?

### ISSUE THREAD

**Issue by Evizero** [JuliaArrays/MosaicViews.jl#2]
Quite some time ago we had a discussion in gitter about such a mosaic package, @timholy. I finally sat down to implement it. I went through our discussion again and incorporated your ideas, which I think greatly improve the design.

The question is now where the package should reside?

---

Basically the package provides an upper case constructor for `MosaicView` which simply uses the third (and optionally fourth)  array dimension to specify the mosaic layout. It's type stable and non-copying. I think this should address the use case you brought up (processing tiled images)

```julia
julia> A = [(k+1)*l-1 for i in 1:2, j in 1:3, k in 1:2, l in 1:2]
2×3×2×2 Array{Int64,4}:
[:, :, 1, 1] =
 1  1  1
 1  1  1

[:, :, 2, 1] =
 2  2  2
 2  2  2

[:, :, 1, 2] =
 3  3  3
 3  3  3

[:, :, 2, 2] =
 5  5  5
 5  5  5

julia> MosaicView(A)
4×6 MosaicViews.MosaicView{Int64,4,Array{Int64,4}}:
 1  1  1  3  3  3
 1  1  1  3  3  3
 2  2  2  5  5  5
 2  2  2  5  5  5
```

This package also provides a lower case function `mosaicview` which is not type stable, but has a number of convenience keyword parameters for layout and padding. The result is still just a view, but it makes use of nesting `ReshapedArray` and `PaddedView`. This addresses my main use case of visualizing images 

```julia
julia> using MosaicViews, Images, MLDatasets

julia> A = MNIST.convert2image(MNIST.traintensor(1:9))
28×28×9 Array{Gray{Float64},3}:
[...]

julia> mosaicview(A, .5, nrow=2, npad=1, rowmajor=true)
57×144 MosaicViews.MosaicView{Gray{Float64},4,...}:
[...]
```

![mosaicview](https://user-images.githubusercontent.com/10854026/34172451-5f80173e-e4f2-11e7-9e86-8b3882d53aa7.png)

**Comment by timholy** [comment]
Awesome!

I don't think there's a clear answer to this question. From the reaction to ImageFiltering, I get the impression that folks think that arrays are much more fundamental than images. So perhaps put it in JuliaArrays?

**Comment by Evizero** [comment]
> So perhaps put it in JuliaArrays?

I also think it's the better choice. To be completely transparent: one reason I asked you on your opinion here was to "probe the waters" on how you feel about moving it to any of those places at all.

**Comment by Evizero** [comment]
I don't seem to have sufficient rights to activate `JuliaArrays/MosaicViews.jl` on travis. would you mind flipping that switch for me?

<img width="177" alt="screen shot 2017-12-21 at 09 36 01" src="https://user-images.githubusercontent.com/10854026/34247352-76c4c638-e632-11e7-97be-3c3a61a67221.png">

**Comment by timholy** [comment]
Done.

**Comment by Evizero** [comment]
perfect, thanks!

**Comment by Evizero** [comment]
Another small request (sorry to be a nuisance). 

It doesn't look like attobot is enabled org wide, so it has to be enabled for this package explicitly. Could you please enable it for MosaicViews? link: https://github.com/integration/attobot

**Comment by Evizero** [comment]
thanks again
